name: 部署vite-vue
on: push

permissions:
    contents: write

jobs:
    job-name:
        name: 工作名称
        runs-on: ubuntu-latest

        steps:
            - name: 读取仓库内容
              uses: actions/checkout@v4

            - name: 读取仓库内容
              run: |
                npm i
                npm run build

            - name: 部署
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: dist                         # 部署的目录
                branch: gh-pages                     # 部署到哪个分支